/**
 * Chess's words in the app's 7 other languages (English is in strings.ts). Each table is a whole `Strings`, so a key
 * added to English and not here fails the typecheck.
 */
import type { Strings } from "./strings.ts";

export const pt: Strings = {
  title: "Xadrez",
  board: "Tabuleiro",
  loading: "Carregando…",
  alone: "Você joga pelos dois lados. Abra o Xadrez numa conversa para jogar com seu contato.",
  waitingPeer: "Esperando seu contato abrir o Xadrez",
  tossing: "Sorteando as cores…",
  yourMove: "Sua vez",
  theirMove: "Vez do contato",
  whiteToMove: "Vez das brancas",
  blackToMove: "Vez das pretas",
  youAreWhite: "Você joga de brancas",
  youAreBlack: "Você joga de pretas",
  check: "Xeque",
  away: "Seu contato fechou o Xadrez. A partida espera aqui.",
  outOfStep: "As partidas de vocês diferem. Começar outra?",
  won: "Você venceu",
  lost: "Você perdeu",
  whiteWins: "Brancas vencem",
  blackWins: "Pretas vencem",
  drawn: "Empate",
  why_checkmate: "xeque-mate",
  why_stalemate: "afogamento",
  why_repetition: "repetição tripla",
  why_fifty: "regra dos 50 lances",
  why_material: "material insuficiente",
  why_limit: "limite de lances",
  why_resign: "desistência",
  why_agreed: "acordo",
  peerOffersDraw: "Seu contato propõe empate",
  youOfferedDraw: "Empate proposto",
  offerDraw: "Propor empate",
  accept: "Aceitar",
  decline: "Recusar",
  resign: "Desistir",
  resignSure: "Desistir? Toque de novo",
  newGame: "Nova partida",
  promoteTo: "Promover a",
  notice_invalidMove: "Um lance inválido do seu contato foi ignorado.",
  notice_badMessage: "Uma mensagem que o Xadrez não entendeu foi ignorada.",
  notice_tooBig: "Uma mensagem grande demais foi ignorada.",
  notice_newerVersion: "Seu contato tem um Xadrez mais novo. Atualize para continuar.",
  notice_badReveal: "O sorteio das cores falhou. Tentando de novo.",
  notice_tossRestarted: "Seu contato recomeçou o sorteio das cores.",
  notice_outOfStep: "As partidas de vocês diferem.",
  notice_peerNewGame: "Seu contato começou uma nova partida.",
  notice_sendFailed: "Não enviado. Vai quando seu contato voltar.",
  white: "brancas",
  black: "pretas",
  piece: "{piece} das {colour}",
  empty: "vazia",
  selected: "selecionada",
  canMoveHere: "mover para cá",
  lastMove: "último lance",
  piece_k: "rei",
  piece_q: "dama",
  piece_r: "torre",
  piece_b: "bispo",
  piece_n: "cavalo",
  piece_p: "peão",
  you: "Você",
  contact: "Seu contato",
  whiteName: "Brancas",
  blackName: "Pretas",
  flip: "Girar tabuleiro",
  settings: "Ajustes",
  close: "Fechar",
  cancel: "Cancelar",
  moves: "Lances",
  set_theme: "Cores do tabuleiro",
  theme_green: "Verde",
  theme_brown: "Marrom",
  theme_blue: "Azul",
  set_pieces: "Peças",
  pieces_cburnett: "Padrão",
  pieces_classic: "Clássicas",
  set_coords: "Mostrar coordenadas",
  set_autoQueen: "Sempre promover a dama",
  set_legal: "Mostrar lances possíveis",
  settingsHint: "Salvo só para esta conversa",
  say_move: "{who}: {piece} para {square}",
  say_capture: "{who}: {piece} captura em {square}",
  say_castleK: "{who}: roque pequeno",
  say_castleQ: "{who}: roque grande",
  say_promote: "promove a {piece}",
  say_check: "xeque",
  say_mate: "xeque-mate",
  nav: "Rever a partida",
  nav_first: "Primeiro lance",
  nav_prev: "Lance anterior",
  nav_play: "Reproduzir os lances",
  nav_pause: "Pausar",
  nav_next: "Próximo lance",
  nav_last: "Último lance",
  backToLive: "Voltar ao jogo",
  review: "Rever",
  opening: "Abertura",
  sound: "Sons",
  taken: "Capturou: {pieces}",
  ahead: "{n} à frente",
  copyPgn: "Copiar PGN",
  pgnTitle: "Partida em PGN",
  copy: "Copiar",
  copied: "Copiado",
  copyByHand: "Copie o texto selecionado (no celular, toque e segure).",
};

export const es: Strings = {
  title: "Ajedrez",
  board: "Tablero",
  loading: "Cargando…",
  alone: "Juegas con ambos colores. Abre Ajedrez en un chat para jugar con tu contacto.",
  waitingPeer: "Esperando a que tu contacto abra Ajedrez",
  tossing: "Sorteando los colores…",
  yourMove: "Tu turno",
  theirMove: "Turno de tu contacto",
  whiteToMove: "Juegan blancas",
  blackToMove: "Juegan negras",
  youAreWhite: "Juegas con blancas",
  youAreBlack: "Juegas con negras",
  check: "Jaque",
  away: "Tu contacto cerró Ajedrez. La partida espera aquí.",
  outOfStep: "Vuestras partidas no coinciden. ¿Empezar otra?",
  won: "Ganas",
  lost: "Pierdes",
  whiteWins: "Ganan blancas",
  blackWins: "Ganan negras",
  drawn: "Tablas",
  why_checkmate: "jaque mate",
  why_stalemate: "ahogado",
  why_repetition: "triple repetición",
  why_fifty: "regla de los 50 movimientos",
  why_material: "material insuficiente",
  why_limit: "límite de jugadas",
  why_resign: "abandono",
  why_agreed: "acuerdo",
  peerOffersDraw: "Tu contacto ofrece tablas",
  youOfferedDraw: "Tablas ofrecidas",
  offerDraw: "Ofrecer tablas",
  accept: "Aceptar",
  decline: "Rechazar",
  resign: "Abandonar",
  resignSure: "¿Abandonar? Pulsa otra vez",
  newGame: "Nueva partida",
  promoteTo: "Promocionar a",
  notice_invalidMove: "Se ignoró una jugada no válida de tu contacto.",
  notice_badMessage: "Se ignoró un mensaje que Ajedrez no pudo leer.",
  notice_tooBig: "Se ignoró un mensaje demasiado grande.",
  notice_newerVersion: "Tu contacto tiene un Ajedrez más nuevo. Actualiza para seguir jugando.",
  notice_badReveal: "Falló el sorteo de colores. Se intenta de nuevo.",
  notice_tossRestarted: "Tu contacto reinició el sorteo de colores.",
  notice_outOfStep: "Vuestras partidas no coinciden.",
  notice_peerNewGame: "Tu contacto empezó una partida nueva.",
  notice_sendFailed: "No enviado. Se enviará cuando tu contacto vuelva.",
  white: "blancas",
  black: "negras",
  piece: "{piece} de las {colour}",
  empty: "vacía",
  selected: "seleccionada",
  canMoveHere: "mover aquí",
  lastMove: "última jugada",
  piece_k: "rey",
  piece_q: "dama",
  piece_r: "torre",
  piece_b: "alfil",
  piece_n: "caballo",
  piece_p: "peón",
  you: "Tú",
  contact: "Tu contacto",
  whiteName: "Blancas",
  blackName: "Negras",
  flip: "Girar tablero",
  settings: "Ajustes",
  close: "Cerrar",
  cancel: "Cancelar",
  moves: "Jugadas",
  set_theme: "Colores del tablero",
  theme_green: "Verde",
  theme_brown: "Marrón",
  theme_blue: "Azul",
  set_pieces: "Piezas",
  pieces_cburnett: "Estándar",
  pieces_classic: "Clásicas",
  set_coords: "Mostrar coordenadas",
  set_autoQueen: "Promocionar siempre a dama",
  set_legal: "Mostrar jugadas posibles",
  settingsHint: "Se guarda solo para este chat",
  say_move: "{who}: {piece} a {square}",
  say_capture: "{who}: {piece} captura en {square}",
  say_castleK: "{who}: enroque corto",
  say_castleQ: "{who}: enroque largo",
  say_promote: "promociona a {piece}",
  say_check: "jaque",
  say_mate: "jaque mate",
  nav: "Revisar la partida",
  nav_first: "Primera jugada",
  nav_prev: "Jugada anterior",
  nav_play: "Reproducir las jugadas",
  nav_pause: "Pausa",
  nav_next: "Jugada siguiente",
  nav_last: "Última jugada",
  backToLive: "Volver a la partida",
  review: "Revisar",
  opening: "Apertura",
  sound: "Sonidos",
  taken: "Capturó: {pieces}",
  ahead: "{n} de ventaja",
  copyPgn: "Copiar PGN",
  pgnTitle: "Partida en PGN",
  copy: "Copiar",
  copied: "Copiado",
  copyByHand: "Copia el texto seleccionado (en el móvil, mantenlo pulsado).",
};

export const fr: Strings = {
  title: "Échecs",
  board: "Échiquier",
  loading: "Chargement…",
  alone: "Vous jouez les deux camps. Ouvrez Échecs dans une discussion pour jouer avec votre contact.",
  waitingPeer: "En attente de votre contact dans Échecs",
  tossing: "Tirage des couleurs…",
  yourMove: "À vous de jouer",
  theirMove: "À votre contact",
  whiteToMove: "Aux blancs de jouer",
  blackToMove: "Aux noirs de jouer",
  youAreWhite: "Vous jouez les blancs",
  youAreBlack: "Vous jouez les noirs",
  check: "Échec",
  away: "Votre contact a fermé Échecs. La partie attend ici.",
  outOfStep: "Vos parties diffèrent. En commencer une autre ?",
  won: "Vous gagnez",
  lost: "Vous perdez",
  whiteWins: "Les blancs gagnent",
  blackWins: "Les noirs gagnent",
  drawn: "Nulle",
  why_checkmate: "échec et mat",
  why_stalemate: "pat",
  why_repetition: "triple répétition",
  why_fifty: "règle des 50 coups",
  why_material: "matériel insuffisant",
  why_limit: "limite de coups",
  why_resign: "abandon",
  why_agreed: "accord",
  peerOffersDraw: "Votre contact propose la nulle",
  youOfferedDraw: "Nulle proposée",
  offerDraw: "Proposer la nulle",
  accept: "Accepter",
  decline: "Refuser",
  resign: "Abandonner",
  resignSure: "Abandonner ? Appuyez encore",
  newGame: "Nouvelle partie",
  promoteTo: "Promouvoir en",
  notice_invalidMove: "Un coup invalide de votre contact a été ignoré.",
  notice_badMessage: "Un message illisible pour Échecs a été ignoré.",
  notice_tooBig: "Un message trop gros a été ignoré.",
  notice_newerVersion: "Votre contact a un Échecs plus récent. Mettez à jour pour continuer.",
  notice_badReveal: "Le tirage des couleurs a échoué. Nouvel essai.",
  notice_tossRestarted: "Votre contact a relancé le tirage des couleurs.",
  notice_outOfStep: "Vos parties diffèrent.",
  notice_peerNewGame: "Votre contact a commencé une nouvelle partie.",
  notice_sendFailed: "Non envoyé. Part dès que votre contact revient.",
  white: "blancs",
  black: "noirs",
  piece: "{piece} des {colour}",
  empty: "vide",
  selected: "sélectionnée",
  canMoveHere: "aller ici",
  lastMove: "dernier coup",
  piece_k: "roi",
  piece_q: "dame",
  piece_r: "tour",
  piece_b: "fou",
  piece_n: "cavalier",
  piece_p: "pion",
  you: "Vous",
  contact: "Votre contact",
  whiteName: "Blancs",
  blackName: "Noirs",
  flip: "Retourner l'échiquier",
  settings: "Réglages",
  close: "Fermer",
  cancel: "Annuler",
  moves: "Coups",
  set_theme: "Couleurs de l'échiquier",
  theme_green: "Vert",
  theme_brown: "Marron",
  theme_blue: "Bleu",
  set_pieces: "Pièces",
  pieces_cburnett: "Par défaut",
  pieces_classic: "Classiques",
  set_coords: "Afficher les coordonnées",
  set_autoQueen: "Toujours promouvoir en dame",
  set_legal: "Afficher les coups possibles",
  settingsHint: "Enregistré pour cette discussion seulement",
  say_move: "{who} : {piece} en {square}",
  say_capture: "{who} : {piece} prend en {square}",
  say_castleK: "{who} : petit roque",
  say_castleQ: "{who} : grand roque",
  say_promote: "promu en {piece}",
  say_check: "échec",
  say_mate: "échec et mat",
  nav: "Revoir la partie",
  nav_first: "Premier coup",
  nav_prev: "Coup précédent",
  nav_play: "Rejouer les coups",
  nav_pause: "Mettre en pause",
  nav_next: "Coup suivant",
  nav_last: "Dernier coup",
  backToLive: "Retour à la partie",
  review: "Revoir",
  opening: "Ouverture",
  sound: "Sons",
  taken: "Pris : {pieces}",
  ahead: "{n} d'avance",
  copyPgn: "Copier le PGN",
  pgnTitle: "Partie en PGN",
  copy: "Copier",
  copied: "Copié",
  copyByHand: "Copiez le texte sélectionné (sur un téléphone, appui long).",
};

export const it: Strings = {
  title: "Scacchi",
  board: "Scacchiera",
  loading: "Caricamento…",
  alone: "Giochi con entrambi i colori. Apri Scacchi in una chat per giocare con il tuo contatto.",
  waitingPeer: "In attesa che il tuo contatto apra Scacchi",
  tossing: "Sorteggio dei colori…",
  yourMove: "Tocca a te",
  theirMove: "Tocca al tuo contatto",
  whiteToMove: "Muove il bianco",
  blackToMove: "Muove il nero",
  youAreWhite: "Giochi con il bianco",
  youAreBlack: "Giochi con il nero",
  check: "Scacco",
  away: "Il tuo contatto ha chiuso Scacchi. La partita aspetta qui.",
  outOfStep: "Le vostre partite non coincidono. Iniziarne un'altra?",
  won: "Hai vinto",
  lost: "Hai perso",
  whiteWins: "Vince il bianco",
  blackWins: "Vince il nero",
  drawn: "Patta",
  why_checkmate: "scacco matto",
  why_stalemate: "stallo",
  why_repetition: "triplice ripetizione",
  why_fifty: "regola delle 50 mosse",
  why_material: "materiale insufficiente",
  why_limit: "limite di mosse",
  why_resign: "abbandono",
  why_agreed: "accordo",
  peerOffersDraw: "Il tuo contatto offre la patta",
  youOfferedDraw: "Patta offerta",
  offerDraw: "Offri la patta",
  accept: "Accetta",
  decline: "Rifiuta",
  resign: "Abbandona",
  resignSure: "Abbandonare? Premi di nuovo",
  newGame: "Nuova partita",
  promoteTo: "Promuovi a",
  notice_invalidMove: "Ignorata una mossa non valida del tuo contatto.",
  notice_badMessage: "Ignorato un messaggio che Scacchi non sa leggere.",
  notice_tooBig: "Ignorato un messaggio troppo grande.",
  notice_newerVersion: "Il tuo contatto ha uno Scacchi più recente. Aggiorna per continuare.",
  notice_badReveal: "Il sorteggio dei colori non è riuscito. Si riprova.",
  notice_tossRestarted: "Il tuo contatto ha ripreso il sorteggio dei colori.",
  notice_outOfStep: "Le vostre partite non coincidono.",
  notice_peerNewGame: "Il tuo contatto ha iniziato una nuova partita.",
  notice_sendFailed: "Non inviato. Parte quando il tuo contatto torna.",
  white: "bianco",
  black: "nero",
  piece: "{piece} del {colour}",
  empty: "vuota",
  selected: "selezionata",
  canMoveHere: "muovi qui",
  lastMove: "ultima mossa",
  piece_k: "re",
  piece_q: "donna",
  piece_r: "torre",
  piece_b: "alfiere",
  piece_n: "cavallo",
  piece_p: "pedone",
  you: "Tu",
  contact: "Il tuo contatto",
  whiteName: "Bianco",
  blackName: "Nero",
  flip: "Ruota la scacchiera",
  settings: "Impostazioni",
  close: "Chiudi",
  cancel: "Annulla",
  moves: "Mosse",
  set_theme: "Colori della scacchiera",
  theme_green: "Verde",
  theme_brown: "Marrone",
  theme_blue: "Blu",
  set_pieces: "Pezzi",
  pieces_cburnett: "Predefiniti",
  pieces_classic: "Classici",
  set_coords: "Mostra le coordinate",
  set_autoQueen: "Promuovi sempre a donna",
  set_legal: "Mostra le mosse possibili",
  settingsHint: "Salvato solo per questa chat",
  say_move: "{who}: {piece} in {square}",
  say_capture: "{who}: {piece} cattura in {square}",
  say_castleK: "{who}: arrocco corto",
  say_castleQ: "{who}: arrocco lungo",
  say_promote: "promosso a {piece}",
  say_check: "scacco",
  say_mate: "scacco matto",
  nav: "Rivedi la partita",
  nav_first: "Prima mossa",
  nav_prev: "Mossa precedente",
  nav_play: "Riproduci le mosse",
  nav_pause: "Pausa",
  nav_next: "Mossa successiva",
  nav_last: "Ultima mossa",
  backToLive: "Torna alla partita",
  review: "Rivedi",
  opening: "Apertura",
  sound: "Suoni",
  taken: "Catturati: {pieces}",
  ahead: "{n} di vantaggio",
  copyPgn: "Copia PGN",
  pgnTitle: "Partita in PGN",
  copy: "Copia",
  copied: "Copiato",
  copyByHand: "Copia il testo selezionato (sul telefono, tieni premuto).",
};

export const ja: Strings = {
  title: "チェス",
  board: "チェス盤",
  loading: "読み込み中…",
  alone: "両方の手番を指しています。チャットでチェスを開くと相手と対局できます。",
  waitingPeer: "相手がチェスを開くのを待っています",
  tossing: "先手後手を決めています…",
  yourMove: "あなたの番",
  theirMove: "相手の番",
  whiteToMove: "白の番",
  blackToMove: "黒の番",
  youAreWhite: "あなたは白",
  youAreBlack: "あなたは黒",
  check: "チェック",
  away: "相手がチェスを閉じました。対局はここで待っています。",
  outOfStep: "対局の内容が一致しません。新しく始めますか？",
  won: "勝ち",
  lost: "負け",
  whiteWins: "白の勝ち",
  blackWins: "黒の勝ち",
  drawn: "引き分け",
  why_checkmate: "チェックメイト",
  why_stalemate: "ステイルメイト",
  why_repetition: "同形三回",
  why_fifty: "50手ルール",
  why_material: "駒不足",
  why_limit: "手数の上限",
  why_resign: "投了",
  why_agreed: "合意",
  peerOffersDraw: "相手が引き分けを提案しています",
  youOfferedDraw: "引き分けを提案済み",
  offerDraw: "引き分けを提案",
  accept: "受ける",
  decline: "断る",
  resign: "投了",
  resignSure: "投了しますか？もう一度押してください",
  newGame: "新しい対局",
  promoteTo: "昇格先",
  notice_invalidMove: "相手の不正な手を無視しました。",
  notice_badMessage: "チェスが読めないメッセージを無視しました。",
  notice_tooBig: "大きすぎるメッセージを無視しました。",
  notice_newerVersion: "相手のチェスの方が新しいです。続けるには更新してください。",
  notice_badReveal: "先手後手の決定に失敗しました。やり直します。",
  notice_tossRestarted: "相手が先手後手の決定をやり直しました。",
  notice_outOfStep: "対局の内容が一致しません。",
  notice_peerNewGame: "相手が新しい対局を始めました。",
  notice_sendFailed: "送信できませんでした。相手が戻ると送られます。",
  white: "白",
  black: "黒",
  piece: "{colour}の{piece}",
  empty: "空き",
  selected: "選択中",
  canMoveHere: "ここに動かせる",
  lastMove: "直前の手",
  piece_k: "キング",
  piece_q: "クイーン",
  piece_r: "ルーク",
  piece_b: "ビショップ",
  piece_n: "ナイト",
  piece_p: "ポーン",
  you: "あなた",
  contact: "相手",
  whiteName: "白",
  blackName: "黒",
  flip: "盤を反転",
  settings: "設定",
  close: "閉じる",
  cancel: "キャンセル",
  moves: "棋譜",
  set_theme: "盤の色",
  theme_green: "緑",
  theme_brown: "茶",
  theme_blue: "青",
  set_pieces: "駒",
  pieces_cburnett: "標準",
  pieces_classic: "クラシック",
  set_coords: "座標を表示",
  set_autoQueen: "常にクイーンに昇格",
  set_legal: "指せる手を表示",
  settingsHint: "このチャットにだけ保存されます",
  say_move: "{who}：{piece}を{square}へ",
  say_capture: "{who}：{piece}が{square}で取る",
  say_castleK: "{who}：キングサイドにキャスリング",
  say_castleQ: "{who}：クイーンサイドにキャスリング",
  say_promote: "{piece}に昇格",
  say_check: "チェック",
  say_mate: "チェックメイト",
  nav: "対局を振り返る",
  nav_first: "最初の手",
  nav_prev: "前の手",
  nav_play: "手を再生",
  nav_pause: "一時停止",
  nav_next: "次の手",
  nav_last: "最後の手",
  backToLive: "対局に戻る",
  review: "振り返る",
  opening: "オープニング",
  sound: "サウンド",
  taken: "取った駒: {pieces}",
  ahead: "{n} 点リード",
  copyPgn: "PGN をコピー",
  pgnTitle: "PGN の棋譜",
  copy: "コピー",
  copied: "コピーしました",
  copyByHand: "選択したテキストをコピーしてください（スマートフォンでは長押し）。",
};

export const zh: Strings = {
  title: "国际象棋",
  board: "棋盘",
  loading: "加载中…",
  alone: "你在同时执两方。在聊天中打开国际象棋即可和联系人对弈。",
  waitingPeer: "等待联系人打开国际象棋",
  tossing: "正在决定执棋颜色…",
  yourMove: "轮到你",
  theirMove: "轮到对方",
  whiteToMove: "白方走",
  blackToMove: "黑方走",
  youAreWhite: "你执白",
  youAreBlack: "你执黑",
  check: "将军",
  away: "联系人关闭了国际象棋。对局在这里等着。",
  outOfStep: "你们的对局不一致。要开始新的一局吗？",
  won: "你赢了",
  lost: "你输了",
  whiteWins: "白方胜",
  blackWins: "黑方胜",
  drawn: "和棋",
  why_checkmate: "将死",
  why_stalemate: "逼和",
  why_repetition: "三次重复",
  why_fifty: "50 步规则",
  why_material: "子力不足",
  why_limit: "步数上限",
  why_resign: "认输",
  why_agreed: "协议",
  peerOffersDraw: "联系人提议和棋",
  youOfferedDraw: "已提议和棋",
  offerDraw: "提议和棋",
  accept: "接受",
  decline: "拒绝",
  resign: "认输",
  resignSure: "认输？再按一次",
  newGame: "新对局",
  promoteTo: "升变为",
  notice_invalidMove: "已忽略联系人的一步无效着法。",
  notice_badMessage: "已忽略一条国际象棋无法读取的消息。",
  notice_tooBig: "已忽略一条过大的消息。",
  notice_newerVersion: "联系人的国际象棋版本更新。请更新后继续。",
  notice_badReveal: "决定颜色失败，正在重试。",
  notice_tossRestarted: "联系人重新开始决定颜色。",
  notice_outOfStep: "你们的对局不一致。",
  notice_peerNewGame: "联系人开始了新对局。",
  notice_sendFailed: "未发送。联系人回来后会发出。",
  white: "白",
  black: "黑",
  piece: "{colour}{piece}",
  empty: "空",
  selected: "已选中",
  canMoveHere: "可走到这里",
  lastMove: "上一步",
  piece_k: "王",
  piece_q: "后",
  piece_r: "车",
  piece_b: "象",
  piece_n: "马",
  piece_p: "兵",
  you: "你",
  contact: "联系人",
  whiteName: "白方",
  blackName: "黑方",
  flip: "翻转棋盘",
  settings: "设置",
  close: "关闭",
  cancel: "取消",
  moves: "着法",
  set_theme: "棋盘颜色",
  theme_green: "绿色",
  theme_brown: "棕色",
  theme_blue: "蓝色",
  set_pieces: "棋子",
  pieces_cburnett: "标准",
  pieces_classic: "经典",
  set_coords: "显示坐标",
  set_autoQueen: "总是升变为后",
  set_legal: "显示可走位置",
  settingsHint: "仅保存在此聊天中",
  say_move: "{who}：{piece}走到{square}",
  say_capture: "{who}：{piece}在{square}吃子",
  say_castleK: "{who}：王翼易位",
  say_castleQ: "{who}：后翼易位",
  say_promote: "升变为{piece}",
  say_check: "将军",
  say_mate: "将死",
  nav: "回顾对局",
  nav_first: "第一步",
  nav_prev: "上一步",
  nav_play: "播放着法",
  nav_pause: "暂停",
  nav_next: "下一步",
  nav_last: "最后一步",
  backToLive: "回到对局",
  review: "回顾",
  opening: "开局",
  sound: "声音",
  taken: "吃掉: {pieces}",
  ahead: "领先 {n}",
  copyPgn: "复制 PGN",
  pgnTitle: "PGN 棋谱",
  copy: "复制",
  copied: "已复制",
  copyByHand: "请复制选中的文字（手机上长按）。",
};

export const ar: Strings = {
  title: "الشطرنج",
  board: "رقعة الشطرنج",
  loading: "جارٍ التحميل…",
  alone: "تلعب بالطرفين. افتح الشطرنج في محادثة لتلعب مع جهة اتصالك.",
  waitingPeer: "بانتظار أن تفتح جهة اتصالك الشطرنج",
  tossing: "جارٍ اختيار الألوان…",
  yourMove: "دورك",
  theirMove: "دور جهة اتصالك",
  whiteToMove: "دور الأبيض",
  blackToMove: "دور الأسود",
  youAreWhite: "تلعب بالأبيض",
  youAreBlack: "تلعب بالأسود",
  check: "كش",
  away: "أغلقت جهة اتصالك الشطرنج. اللعبة تنتظر هنا.",
  outOfStep: "لعبتاكما مختلفتان. هل تبدأ لعبة جديدة؟",
  won: "فزت",
  lost: "خسرت",
  whiteWins: "فاز الأبيض",
  blackWins: "فاز الأسود",
  drawn: "تعادل",
  why_checkmate: "كش مات",
  why_stalemate: "جمود",
  why_repetition: "تكرار ثلاثي",
  why_fifty: "قاعدة الخمسين نقلة",
  why_material: "قطع غير كافية",
  why_limit: "حد النقلات",
  why_resign: "استسلام",
  why_agreed: "اتفاق",
  peerOffersDraw: "تعرض جهة اتصالك التعادل",
  youOfferedDraw: "عُرض التعادل",
  offerDraw: "اعرض التعادل",
  accept: "قبول",
  decline: "رفض",
  resign: "استسلام",
  resignSure: "تستسلم؟ اضغط مرة أخرى",
  newGame: "لعبة جديدة",
  promoteTo: "ترقية إلى",
  notice_invalidMove: "تم تجاهل نقلة غير صالحة من جهة اتصالك.",
  notice_badMessage: "تم تجاهل رسالة لم يستطع الشطرنج قراءتها.",
  notice_tooBig: "تم تجاهل رسالة كبيرة جدًا.",
  notice_newerVersion: "لدى جهة اتصالك إصدار أحدث من الشطرنج. حدّث لتواصل اللعب.",
  notice_badReveal: "فشل اختيار الألوان. جارٍ المحاولة مجددًا.",
  notice_tossRestarted: "أعادت جهة اتصالك اختيار الألوان.",
  notice_outOfStep: "لعبتاكما مختلفتان.",
  notice_peerNewGame: "بدأت جهة اتصالك لعبة جديدة.",
  notice_sendFailed: "لم تُرسل. ستُرسل عند عودة جهة اتصالك.",
  white: "أبيض",
  black: "أسود",
  piece: "{piece} {colour}",
  empty: "فارغ",
  selected: "محدد",
  canMoveHere: "انقل إلى هنا",
  lastMove: "آخر نقلة",
  piece_k: "ملك",
  piece_q: "وزير",
  piece_r: "رخ",
  piece_b: "فيل",
  piece_n: "حصان",
  piece_p: "بيدق",
  you: "أنت",
  contact: "جهة اتصالك",
  whiteName: "الأبيض",
  blackName: "الأسود",
  flip: "اقلب الرقعة",
  settings: "الإعدادات",
  close: "إغلاق",
  cancel: "إلغاء",
  moves: "النقلات",
  set_theme: "ألوان الرقعة",
  theme_green: "أخضر",
  theme_brown: "بني",
  theme_blue: "أزرق",
  set_pieces: "القطع",
  pieces_cburnett: "قياسية",
  pieces_classic: "كلاسيكية",
  set_coords: "إظهار الإحداثيات",
  set_autoQueen: "الترقية إلى وزير دائمًا",
  set_legal: "إظهار النقلات الممكنة",
  settingsHint: "تُحفظ لهذه المحادثة فقط",
  say_move: "{who}: {piece} إلى {square}",
  say_capture: "{who}: {piece} يأسر في {square}",
  say_castleK: "{who}: تبييت قصير",
  say_castleQ: "{who}: تبييت طويل",
  say_promote: "يترقى إلى {piece}",
  say_check: "كش",
  say_mate: "كش مات",
  nav: "مراجعة اللعبة",
  nav_first: "النقلة الأولى",
  nav_prev: "النقلة السابقة",
  nav_play: "تشغيل النقلات",
  nav_pause: "إيقاف مؤقت",
  nav_next: "النقلة التالية",
  nav_last: "النقلة الأخيرة",
  backToLive: "العودة إلى اللعبة",
  review: "مراجعة",
  opening: "الافتتاح",
  sound: "الأصوات",
  taken: "أخذ: {pieces}",
  ahead: "متقدم بـ {n}",
  copyPgn: "نسخ PGN",
  pgnTitle: "اللعبة بصيغة PGN",
  copy: "نسخ",
  copied: "تم النسخ",
  copyByHand: "انسخ النص المحدد (على الهاتف، اضغط عليه مطولًا).",
};
