/**
 * Chess's words in the app's 7 other languages (English is in strings.ts). Each table is a whole `Strings`, so a key
 * added to English and not here fails the typecheck.
 */
import type { Strings } from "./strings.ts";

export const pt: Strings = {
  title: "Xadrez",
  board: "Tabuleiro",
  loading: "Carregando…",
  alone: "Você joga pelos dois lados. Abra o Xadrez numa conversa para jogar com seu contato.",
  waitingPeer: "Esperando seu contato abrir o Xadrez",
  tossing: "Sorteando as cores…",
  yourMove: "Sua vez",
  theirMove: "Vez do contato",
  whiteToMove: "Vez das brancas",
  blackToMove: "Vez das pretas",
  youAreWhite: "Você joga de brancas",
  youAreBlack: "Você joga de pretas",
  check: "Xeque",
  away: "Seu contato fechou o Xadrez. A partida espera aqui.",
  outOfStep: "As partidas de vocês diferem. Começar outra?",
  won: "Você venceu",
  lost: "Você perdeu",
  whiteWins: "Brancas vencem",
  blackWins: "Pretas vencem",
  drawn: "Empate",
  why_checkmate: "xeque-mate",
  why_stalemate: "afogamento",
  why_repetition: "repetição tripla",
  why_fifty: "regra dos 50 lances",
  why_material: "material insuficiente",
  why_limit: "limite de lances",
  why_resign: "desistência",
  why_agreed: "acordo",
  peerOffersDraw: "Seu contato propõe empate",
  youOfferedDraw: "Empate proposto",
  offerDraw: "Propor empate",
  accept: "Aceitar",
  decline: "Recusar",
  resign: "Desistir",
  newGame: "Nova partida",
  promoteTo: "Promover a",
  notice_invalidMove: "Um lance inválido do seu contato foi ignorado.",
  notice_badMessage: "Uma mensagem que o Xadrez não entendeu foi ignorada.",
  notice_tooBig: "Uma mensagem grande demais foi ignorada.",
  notice_newerVersion: "Seu contato tem um Xadrez mais novo. Atualize para continuar.",
  notice_badReveal: "O sorteio das cores falhou. Tentando de novo.",
  notice_tossRestarted: "Seu contato recomeçou o sorteio das cores.",
  notice_outOfStep: "As partidas de vocês diferem.",
  notice_peerNewGame: "Seu contato começou uma nova partida.",
  notice_sendFailed: "Não enviado. Vai quando seu contato voltar.",
  white: "brancas",
  black: "pretas",
  piece: "{piece} das {colour}",
  empty: "vazia",
  selected: "selecionada",
  canMoveHere: "mover para cá",
  lastMove: "último lance",
  piece_k: "rei",
  piece_q: "dama",
  piece_r: "torre",
  piece_b: "bispo",
  piece_n: "cavalo",
  piece_p: "peão",
  you: "Você",
  contact: "Seu contato",
  whiteName: "Brancas",
  blackName: "Pretas",
  flip: "Girar tabuleiro",
  settings: "Ajustes",
  close: "Fechar",
  cancel: "Cancelar",
  moves: "Lances",
  set_theme: "Cores do tabuleiro",
  theme_green: "Verde",
  theme_brown: "Marrom",
  theme_blue: "Azul",
  set_pieces: "Peças",
  pieces_cburnett: "Padrão",
  pieces_classic: "Clássicas",
  set_coords: "Mostrar coordenadas",
  set_autoQueen: "Sempre promover a dama",
  set_legal: "Mostrar lances possíveis",
  settingsHint: "Salvo só para esta conversa",
  say_move: "{who}: {piece} para {square}",
  say_capture: "{who}: {piece} captura em {square}",
  say_castleK: "{who}: roque pequeno",
  say_castleQ: "{who}: roque grande",
  say_promote: "promove a {piece}",
  say_check: "xeque",
  say_mate: "xeque-mate",
  nav: "Rever a partida",
  nav_first: "Primeiro lance",
  nav_prev: "Lance anterior",
  nav_play: "Reproduzir os lances",
  nav_pause: "Pausar",
  nav_next: "Próximo lance",
  nav_last: "Último lance",
  backToLive: "Voltar ao jogo",
  review: "Rever",
  opening: "Abertura",
  sound: "Sons",
  taken: "Capturou: {pieces}",
  ahead: "{n} à frente",
  copyPgn: "Copiar PGN",
  pgnTitle: "Partida em PGN",
  copy: "Copiar",
  copied: "Copiado",
  copyByHand: "Copie o texto selecionado (no celular, toque e segure).",
  why_time: "tempo",
  why_aborted: "anulada",
  why_disputed: "relógios em desacordo",
  noResult: "Sem resultado",
  notice_declined: "Seu contato recusou o convite.",
  setupTitle: "Nova partida",
  setupHint: "O sorteio decide quem joga de brancas.",
  tc_unlimited: "Sem limite",
  tc_bullet: "Bullet",
  tc_blitz: "Blitz",
  tc_rapid: "Rápida",
  tc_classical: "Clássica",
  tc_words: "{kind}, {min} min",
  tc_wordsInc: "{kind}, {min} min + {inc} s",
  invite: "Convidar",
  setupStatus: "Convide seu contato para uma partida",
  invitedStatus: "Convite enviado",
  invitedAway: "Seu convite vai quando seu contato abrir o Xadrez.",
  invitesYou: "Seu contato convida você: {terms}",
  rematchYou: "Revanche? ({terms})",
  canStillMove: "Você ainda pode fazer seu lance. Ele vai quando seu contato voltar.",
  compatBanner: "Seu contato tem o Xadrez {version}. Relógios, voltar lances e revanches chegam quando ele atualizar.",
  compatBannerOld: "Seu contato tem um Xadrez mais antigo. Relógios, voltar lances e revanches chegam quando ele atualizar.",
  compatInfo: "Sobre isto",
  compatDetails: "O Xadrez do seu contato fala a primeira versão do protocolo do jogo: vocês jogam partidas sem relógio, e uma partida começada continua quando qualquer um de vocês atualizar. O Ghostly atualiza os apps ao abrir, uma vez por dia e na página Apps.",
  needsUpdate: "Seu contato precisa atualizar o Xadrez (ele tem a {version})",
  needsUpdateOld: "Seu contato precisa atualizar o Xadrez",
  comingSoon: "Chega numa próxima versão do Xadrez",
  why_timeMaterial: "tempo contra material insuficiente",
  notice_clockOff: "O relógio do seu contato parece errado.",
  peerSilent: "O Xadrez do seu contato não está respondendo",
  pendingClaim: "O tempo do seu contato está acabando. A partida termina quando ele voltar ao Xadrez.",
  say_secondsLeft: "Restam {n} segundos",
  takeback: "Voltar lance",
  takebackAsked: "Volta pedida",
  peerAsksTakeback: "Seu contato pede para voltar um lance",
  takenBack: "Lance desfeito",
  notice_takebackDeclined: "Seu contato recusou voltar o lance.",
  rematch: "Revanche",
  resignAsk: "Desistir desta partida?",
  abort: "Anular",
  set_premove: "Permitir pré-lances",
  premove: "pré-lance",
};

export const es: Strings = {
  title: "Ajedrez",
  board: "Tablero",
  loading: "Cargando…",
  alone: "Juegas con ambos colores. Abre Ajedrez en un chat para jugar con tu contacto.",
  waitingPeer: "Esperando a que tu contacto abra Ajedrez",
  tossing: "Sorteando los colores…",
  yourMove: "Tu turno",
  theirMove: "Turno de tu contacto",
  whiteToMove: "Juegan blancas",
  blackToMove: "Juegan negras",
  youAreWhite: "Juegas con blancas",
  youAreBlack: "Juegas con negras",
  check: "Jaque",
  away: "Tu contacto cerró Ajedrez. La partida espera aquí.",
  outOfStep: "Vuestras partidas no coinciden. ¿Empezar otra?",
  won: "Ganas",
  lost: "Pierdes",
  whiteWins: "Ganan blancas",
  blackWins: "Ganan negras",
  drawn: "Tablas",
  why_checkmate: "jaque mate",
  why_stalemate: "ahogado",
  why_repetition: "triple repetición",
  why_fifty: "regla de los 50 movimientos",
  why_material: "material insuficiente",
  why_limit: "límite de jugadas",
  why_resign: "abandono",
  why_agreed: "acuerdo",
  peerOffersDraw: "Tu contacto ofrece tablas",
  youOfferedDraw: "Tablas ofrecidas",
  offerDraw: "Ofrecer tablas",
  accept: "Aceptar",
  decline: "Rechazar",
  resign: "Abandonar",
  newGame: "Nueva partida",
  promoteTo: "Promocionar a",
  notice_invalidMove: "Se ignoró una jugada no válida de tu contacto.",
  notice_badMessage: "Se ignoró un mensaje que Ajedrez no pudo leer.",
  notice_tooBig: "Se ignoró un mensaje demasiado grande.",
  notice_newerVersion: "Tu contacto tiene un Ajedrez más nuevo. Actualiza para seguir jugando.",
  notice_badReveal: "Falló el sorteo de colores. Se intenta de nuevo.",
  notice_tossRestarted: "Tu contacto reinició el sorteo de colores.",
  notice_outOfStep: "Vuestras partidas no coinciden.",
  notice_peerNewGame: "Tu contacto empezó una partida nueva.",
  notice_sendFailed: "No enviado. Se enviará cuando tu contacto vuelva.",
  white: "blancas",
  black: "negras",
  piece: "{piece} de las {colour}",
  empty: "vacía",
  selected: "seleccionada",
  canMoveHere: "mover aquí",
  lastMove: "última jugada",
  piece_k: "rey",
  piece_q: "dama",
  piece_r: "torre",
  piece_b: "alfil",
  piece_n: "caballo",
  piece_p: "peón",
  you: "Tú",
  contact: "Tu contacto",
  whiteName: "Blancas",
  blackName: "Negras",
  flip: "Girar tablero",
  settings: "Ajustes",
  close: "Cerrar",
  cancel: "Cancelar",
  moves: "Jugadas",
  set_theme: "Colores del tablero",
  theme_green: "Verde",
  theme_brown: "Marrón",
  theme_blue: "Azul",
  set_pieces: "Piezas",
  pieces_cburnett: "Estándar",
  pieces_classic: "Clásicas",
  set_coords: "Mostrar coordenadas",
  set_autoQueen: "Promocionar siempre a dama",
  set_legal: "Mostrar jugadas posibles",
  settingsHint: "Se guarda solo para este chat",
  say_move: "{who}: {piece} a {square}",
  say_capture: "{who}: {piece} captura en {square}",
  say_castleK: "{who}: enroque corto",
  say_castleQ: "{who}: enroque largo",
  say_promote: "promociona a {piece}",
  say_check: "jaque",
  say_mate: "jaque mate",
  nav: "Revisar la partida",
  nav_first: "Primera jugada",
  nav_prev: "Jugada anterior",
  nav_play: "Reproducir las jugadas",
  nav_pause: "Pausa",
  nav_next: "Jugada siguiente",
  nav_last: "Última jugada",
  backToLive: "Volver a la partida",
  review: "Revisar",
  opening: "Apertura",
  sound: "Sonidos",
  taken: "Capturó: {pieces}",
  ahead: "{n} de ventaja",
  copyPgn: "Copiar PGN",
  pgnTitle: "Partida en PGN",
  copy: "Copiar",
  copied: "Copiado",
  copyByHand: "Copia el texto seleccionado (en el móvil, mantenlo pulsado).",
  why_time: "tiempo",
  why_aborted: "anulada",
  why_disputed: "relojes en desacuerdo",
  noResult: "Sin resultado",
  notice_declined: "Tu contacto rechazó la invitación.",
  setupTitle: "Nueva partida",
  setupHint: "El sorteo decide quién juega con blancas.",
  tc_unlimited: "Sin límite",
  tc_bullet: "Bullet",
  tc_blitz: "Blitz",
  tc_rapid: "Rápida",
  tc_classical: "Clásica",
  tc_words: "{kind}, {min} min",
  tc_wordsInc: "{kind}, {min} min + {inc} s",
  invite: "Invitar",
  setupStatus: "Invita a tu contacto a una partida",
  invitedStatus: "Invitación enviada",
  invitedAway: "Tu invitación sale cuando tu contacto abra Ajedrez.",
  invitesYou: "Tu contacto te invita: {terms}",
  rematchYou: "¿Revancha? ({terms})",
  canStillMove: "Aún puedes hacer tu jugada. Sale cuando tu contacto vuelva.",
  compatBanner: "Tu contacto tiene Ajedrez {version}. Relojes, deshacer jugadas y revanchas llegan cuando actualice.",
  compatBannerOld: "Tu contacto tiene un Ajedrez más antiguo. Relojes, deshacer jugadas y revanchas llegan cuando actualice.",
  compatInfo: "Acerca de esto",
  compatDetails: "El Ajedrez de tu contacto habla la primera versión del protocolo del juego: jugáis partidas sin reloj, y una partida empezada sigue cuando cualquiera de los dos actualice. Ghostly actualiza las apps al iniciar, una vez al día y en la página Apps.",
  needsUpdate: "Tu contacto tiene que actualizar Ajedrez (tiene la {version})",
  needsUpdateOld: "Tu contacto tiene que actualizar Ajedrez",
  comingSoon: "Llega en una próxima versión de Ajedrez",
  why_timeMaterial: "tiempo contra material insuficiente",
  notice_clockOff: "El reloj de tu contacto parece desajustado.",
  peerSilent: "Tu contacto no responde en Ajedrez",
  pendingClaim: "El tiempo de tu contacto se acaba. La partida termina cuando vuelva a Ajedrez.",
  say_secondsLeft: "Quedan {n} segundos",
  takeback: "Deshacer jugada",
  takebackAsked: "Deshacer pedido",
  peerAsksTakeback: "Tu contacto pide deshacer una jugada",
  takenBack: "Jugada deshecha",
  notice_takebackDeclined: "Tu contacto rechazó deshacer la jugada.",
  rematch: "Revancha",
  resignAsk: "¿Abandonar esta partida?",
  abort: "Anular",
  set_premove: "Permitir premovimientos",
  premove: "premovimiento",
};

export const fr: Strings = {
  title: "Échecs",
  board: "Échiquier",
  loading: "Chargement…",
  alone: "Vous jouez les deux camps. Ouvrez Échecs dans une discussion pour jouer avec votre contact.",
  waitingPeer: "En attente de votre contact dans Échecs",
  tossing: "Tirage des couleurs…",
  yourMove: "À vous de jouer",
  theirMove: "À votre contact",
  whiteToMove: "Aux blancs de jouer",
  blackToMove: "Aux noirs de jouer",
  youAreWhite: "Vous jouez les blancs",
  youAreBlack: "Vous jouez les noirs",
  check: "Échec",
  away: "Votre contact a fermé Échecs. La partie attend ici.",
  outOfStep: "Vos parties diffèrent. En commencer une autre ?",
  won: "Vous gagnez",
  lost: "Vous perdez",
  whiteWins: "Les blancs gagnent",
  blackWins: "Les noirs gagnent",
  drawn: "Nulle",
  why_checkmate: "échec et mat",
  why_stalemate: "pat",
  why_repetition: "triple répétition",
  why_fifty: "règle des 50 coups",
  why_material: "matériel insuffisant",
  why_limit: "limite de coups",
  why_resign: "abandon",
  why_agreed: "accord",
  peerOffersDraw: "Votre contact propose la nulle",
  youOfferedDraw: "Nulle proposée",
  offerDraw: "Proposer nulle",
  accept: "Accepter",
  decline: "Refuser",
  resign: "Abandonner",
  newGame: "Nouvelle partie",
  promoteTo: "Promouvoir en",
  notice_invalidMove: "Un coup invalide de votre contact a été ignoré.",
  notice_badMessage: "Un message illisible pour Échecs a été ignoré.",
  notice_tooBig: "Un message trop gros a été ignoré.",
  notice_newerVersion: "Votre contact a un Échecs plus récent. Mettez à jour pour continuer.",
  notice_badReveal: "Le tirage des couleurs a échoué. Nouvel essai.",
  notice_tossRestarted: "Votre contact a relancé le tirage des couleurs.",
  notice_outOfStep: "Vos parties diffèrent.",
  notice_peerNewGame: "Votre contact a commencé une nouvelle partie.",
  notice_sendFailed: "Non envoyé. Part dès que votre contact revient.",
  white: "blancs",
  black: "noirs",
  piece: "{piece} des {colour}",
  empty: "vide",
  selected: "sélectionnée",
  canMoveHere: "aller ici",
  lastMove: "dernier coup",
  piece_k: "roi",
  piece_q: "dame",
  piece_r: "tour",
  piece_b: "fou",
  piece_n: "cavalier",
  piece_p: "pion",
  you: "Vous",
  contact: "Votre contact",
  whiteName: "Blancs",
  blackName: "Noirs",
  flip: "Retourner l'échiquier",
  settings: "Réglages",
  close: "Fermer",
  cancel: "Annuler",
  moves: "Coups",
  set_theme: "Couleurs de l'échiquier",
  theme_green: "Vert",
  theme_brown: "Marron",
  theme_blue: "Bleu",
  set_pieces: "Pièces",
  pieces_cburnett: "Par défaut",
  pieces_classic: "Classiques",
  set_coords: "Afficher les coordonnées",
  set_autoQueen: "Toujours promouvoir en dame",
  set_legal: "Afficher les coups possibles",
  settingsHint: "Enregistré pour cette discussion seulement",
  say_move: "{who} : {piece} en {square}",
  say_capture: "{who} : {piece} prend en {square}",
  say_castleK: "{who} : petit roque",
  say_castleQ: "{who} : grand roque",
  say_promote: "promu en {piece}",
  say_check: "échec",
  say_mate: "échec et mat",
  nav: "Revoir la partie",
  nav_first: "Premier coup",
  nav_prev: "Coup précédent",
  nav_play: "Rejouer les coups",
  nav_pause: "Mettre en pause",
  nav_next: "Coup suivant",
  nav_last: "Dernier coup",
  backToLive: "Retour à la partie",
  review: "Revoir",
  opening: "Ouverture",
  sound: "Sons",
  taken: "Pris : {pieces}",
  ahead: "{n} d'avance",
  copyPgn: "Copier le PGN",
  pgnTitle: "Partie en PGN",
  copy: "Copier",
  copied: "Copié",
  copyByHand: "Copiez le texte sélectionné (sur un téléphone, appui long).",
  why_time: "temps",
  why_aborted: "annulée",
  why_disputed: "pendules en désaccord",
  noResult: "Pas de résultat",
  notice_declined: "Votre contact a refusé l'invitation.",
  setupTitle: "Nouvelle partie",
  setupHint: "Le tirage au sort décide qui a les blancs.",
  tc_unlimited: "Illimité",
  tc_bullet: "Bullet",
  tc_blitz: "Blitz",
  tc_rapid: "Rapide",
  tc_classical: "Classique",
  tc_words: "{kind}, {min} min",
  tc_wordsInc: "{kind}, {min} min + {inc} s",
  invite: "Inviter",
  setupStatus: "Invitez votre contact à une partie",
  invitedStatus: "Invitation envoyée",
  invitedAway: "Votre invitation part quand votre contact ouvre Échecs.",
  invitesYou: "Votre contact vous invite : {terms}",
  rematchYou: "Revanche ? ({terms})",
  canStillMove: "Vous pouvez encore jouer votre coup. Il part quand votre contact revient.",
  compatBanner: "Votre contact a Échecs {version}. Pendules, reprises de coups et revanches viendront quand il mettra à jour.",
  compatBannerOld: "Votre contact a un Échecs plus ancien. Pendules, reprises de coups et revanches viendront quand il mettra à jour.",
  compatInfo: "À propos",
  compatDetails: "L'Échecs de votre contact parle la première version du protocole du jeu : vous jouez sans pendule, et une partie commencée continue quand l'un de vous met à jour. Ghostly met les apps à jour au démarrage, une fois par jour et sur la page Apps.",
  needsUpdate: "Votre contact doit mettre à jour Échecs (il a la {version})",
  needsUpdateOld: "Votre contact doit mettre à jour Échecs",
  comingSoon: "Arrive dans une prochaine version d'Échecs",
  why_timeMaterial: "temps contre matériel insuffisant",
  notice_clockOff: "La pendule de votre contact semble décalée.",
  peerSilent: "Échecs ne répond pas chez votre contact",
  pendingClaim: "Le temps de votre contact s'épuise. La partie se termine à son retour sur Échecs.",
  say_secondsLeft: "Il reste {n} secondes",
  takeback: "Reprendre le coup",
  takebackAsked: "Reprise demandée",
  peerAsksTakeback: "Votre contact demande à reprendre un coup",
  takenBack: "Coup repris",
  notice_takebackDeclined: "Votre contact a refusé la reprise.",
  rematch: "Revanche",
  resignAsk: "Abandonner cette partie ?",
  abort: "Annuler la partie",
  set_premove: "Autoriser les pré-coups",
  premove: "pré-coup",
};

export const it: Strings = {
  title: "Scacchi",
  board: "Scacchiera",
  loading: "Caricamento…",
  alone: "Giochi con entrambi i colori. Apri Scacchi in una chat per giocare con il tuo contatto.",
  waitingPeer: "In attesa che il tuo contatto apra Scacchi",
  tossing: "Sorteggio dei colori…",
  yourMove: "Tocca a te",
  theirMove: "Tocca al tuo contatto",
  whiteToMove: "Muove il bianco",
  blackToMove: "Muove il nero",
  youAreWhite: "Giochi con il bianco",
  youAreBlack: "Giochi con il nero",
  check: "Scacco",
  away: "Il tuo contatto ha chiuso Scacchi. La partita aspetta qui.",
  outOfStep: "Le vostre partite non coincidono. Iniziarne un'altra?",
  won: "Hai vinto",
  lost: "Hai perso",
  whiteWins: "Vince il bianco",
  blackWins: "Vince il nero",
  drawn: "Patta",
  why_checkmate: "scacco matto",
  why_stalemate: "stallo",
  why_repetition: "triplice ripetizione",
  why_fifty: "regola delle 50 mosse",
  why_material: "materiale insufficiente",
  why_limit: "limite di mosse",
  why_resign: "abbandono",
  why_agreed: "accordo",
  peerOffersDraw: "Il tuo contatto offre la patta",
  youOfferedDraw: "Patta offerta",
  offerDraw: "Offri la patta",
  accept: "Accetta",
  decline: "Rifiuta",
  resign: "Abbandona",
  newGame: "Nuova partita",
  promoteTo: "Promuovi a",
  notice_invalidMove: "Ignorata una mossa non valida del tuo contatto.",
  notice_badMessage: "Ignorato un messaggio che Scacchi non sa leggere.",
  notice_tooBig: "Ignorato un messaggio troppo grande.",
  notice_newerVersion: "Il tuo contatto ha uno Scacchi più recente. Aggiorna per continuare.",
  notice_badReveal: "Il sorteggio dei colori non è riuscito. Si riprova.",
  notice_tossRestarted: "Il tuo contatto ha ripreso il sorteggio dei colori.",
  notice_outOfStep: "Le vostre partite non coincidono.",
  notice_peerNewGame: "Il tuo contatto ha iniziato una nuova partita.",
  notice_sendFailed: "Non inviato. Parte quando il tuo contatto torna.",
  white: "bianco",
  black: "nero",
  piece: "{piece} del {colour}",
  empty: "vuota",
  selected: "selezionata",
  canMoveHere: "muovi qui",
  lastMove: "ultima mossa",
  piece_k: "re",
  piece_q: "donna",
  piece_r: "torre",
  piece_b: "alfiere",
  piece_n: "cavallo",
  piece_p: "pedone",
  you: "Tu",
  contact: "Il tuo contatto",
  whiteName: "Bianco",
  blackName: "Nero",
  flip: "Ruota la scacchiera",
  settings: "Impostazioni",
  close: "Chiudi",
  cancel: "Annulla",
  moves: "Mosse",
  set_theme: "Colori della scacchiera",
  theme_green: "Verde",
  theme_brown: "Marrone",
  theme_blue: "Blu",
  set_pieces: "Pezzi",
  pieces_cburnett: "Predefiniti",
  pieces_classic: "Classici",
  set_coords: "Mostra le coordinate",
  set_autoQueen: "Promuovi sempre a donna",
  set_legal: "Mostra le mosse possibili",
  settingsHint: "Salvato solo per questa chat",
  say_move: "{who}: {piece} in {square}",
  say_capture: "{who}: {piece} cattura in {square}",
  say_castleK: "{who}: arrocco corto",
  say_castleQ: "{who}: arrocco lungo",
  say_promote: "promosso a {piece}",
  say_check: "scacco",
  say_mate: "scacco matto",
  nav: "Rivedi la partita",
  nav_first: "Prima mossa",
  nav_prev: "Mossa precedente",
  nav_play: "Riproduci le mosse",
  nav_pause: "Pausa",
  nav_next: "Mossa successiva",
  nav_last: "Ultima mossa",
  backToLive: "Torna alla partita",
  review: "Rivedi",
  opening: "Apertura",
  sound: "Suoni",
  taken: "Catturati: {pieces}",
  ahead: "{n} di vantaggio",
  copyPgn: "Copia PGN",
  pgnTitle: "Partita in PGN",
  copy: "Copia",
  copied: "Copiato",
  copyByHand: "Copia il testo selezionato (sul telefono, tieni premuto).",
  why_time: "tempo",
  why_aborted: "annullata",
  why_disputed: "orologi in disaccordo",
  noResult: "Nessun risultato",
  notice_declined: "Il tuo contatto ha rifiutato l'invito.",
  setupTitle: "Nuova partita",
  setupHint: "Il sorteggio decide chi gioca col bianco.",
  tc_unlimited: "Senza limite",
  tc_bullet: "Bullet",
  tc_blitz: "Blitz",
  tc_rapid: "Rapida",
  tc_classical: "Classica",
  tc_words: "{kind}, {min} min",
  tc_wordsInc: "{kind}, {min} min + {inc} s",
  invite: "Invita",
  setupStatus: "Invita il tuo contatto a una partita",
  invitedStatus: "Invito inviato",
  invitedAway: "Il tuo invito parte quando il tuo contatto apre Scacchi.",
  invitesYou: "Il tuo contatto ti invita: {terms}",
  rematchYou: "Rivincita? ({terms})",
  canStillMove: "Puoi ancora fare la tua mossa. Parte quando il tuo contatto torna.",
  compatBanner: "Il tuo contatto ha Scacchi {version}. Orologi, ritiro delle mosse e rivincite arrivano quando aggiorna.",
  compatBannerOld: "Il tuo contatto ha uno Scacchi più vecchio. Orologi, ritiro delle mosse e rivincite arrivano quando aggiorna.",
  compatInfo: "Informazioni",
  compatDetails: "Lo Scacchi del tuo contatto parla la prima versione del protocollo del gioco: giocate partite senza orologio, e una partita iniziata continua quando uno di voi aggiorna. Ghostly aggiorna le app all'avvio, una volta al giorno e nella pagina App.",
  needsUpdate: "Il tuo contatto deve aggiornare Scacchi (ha la {version})",
  needsUpdateOld: "Il tuo contatto deve aggiornare Scacchi",
  comingSoon: "Arriva in una prossima versione di Scacchi",
  why_timeMaterial: "tempo contro materiale insufficiente",
  notice_clockOff: "L'orologio del tuo contatto sembra sbagliato.",
  peerSilent: "Scacchi non risponde dal tuo contatto",
  pendingClaim: "Il tempo del tuo contatto sta finendo. La partita finisce al suo ritorno su Scacchi.",
  say_secondsLeft: "Restano {n} secondi",
  takeback: "Ritira la mossa",
  takebackAsked: "Ritiro chiesto",
  peerAsksTakeback: "Il tuo contatto chiede di ritirare una mossa",
  takenBack: "Mossa ritirata",
  notice_takebackDeclined: "Il tuo contatto ha rifiutato il ritiro.",
  rematch: "Rivincita",
  resignAsk: "Abbandonare questa partita?",
  abort: "Annulla partita",
  set_premove: "Consenti le premosse",
  premove: "premossa",
};

export const ja: Strings = {
  title: "チェス",
  board: "チェス盤",
  loading: "読み込み中…",
  alone: "両方の手番を指しています。チャットでチェスを開くと相手と対局できます。",
  waitingPeer: "相手がチェスを開くのを待っています",
  tossing: "先手後手を決めています…",
  yourMove: "あなたの番",
  theirMove: "相手の番",
  whiteToMove: "白の番",
  blackToMove: "黒の番",
  youAreWhite: "あなたは白",
  youAreBlack: "あなたは黒",
  check: "チェック",
  away: "相手がチェスを閉じました。対局はここで待っています。",
  outOfStep: "対局の内容が一致しません。新しく始めますか？",
  won: "勝ち",
  lost: "負け",
  whiteWins: "白の勝ち",
  blackWins: "黒の勝ち",
  drawn: "引き分け",
  why_checkmate: "チェックメイト",
  why_stalemate: "ステイルメイト",
  why_repetition: "同形三回",
  why_fifty: "50手ルール",
  why_material: "駒不足",
  why_limit: "手数の上限",
  why_resign: "投了",
  why_agreed: "合意",
  peerOffersDraw: "相手が引き分けを提案しています",
  youOfferedDraw: "引き分けを提案済み",
  offerDraw: "引き分けを提案",
  accept: "受ける",
  decline: "断る",
  resign: "投了",
  newGame: "新しい対局",
  promoteTo: "昇格先",
  notice_invalidMove: "相手の不正な手を無視しました。",
  notice_badMessage: "チェスが読めないメッセージを無視しました。",
  notice_tooBig: "大きすぎるメッセージを無視しました。",
  notice_newerVersion: "相手のチェスの方が新しいです。続けるには更新してください。",
  notice_badReveal: "先手後手の決定に失敗しました。やり直します。",
  notice_tossRestarted: "相手が先手後手の決定をやり直しました。",
  notice_outOfStep: "対局の内容が一致しません。",
  notice_peerNewGame: "相手が新しい対局を始めました。",
  notice_sendFailed: "送信できませんでした。相手が戻ると送られます。",
  white: "白",
  black: "黒",
  piece: "{colour}の{piece}",
  empty: "空き",
  selected: "選択中",
  canMoveHere: "ここに動かせる",
  lastMove: "直前の手",
  piece_k: "キング",
  piece_q: "クイーン",
  piece_r: "ルーク",
  piece_b: "ビショップ",
  piece_n: "ナイト",
  piece_p: "ポーン",
  you: "あなた",
  contact: "相手",
  whiteName: "白",
  blackName: "黒",
  flip: "盤を反転",
  settings: "設定",
  close: "閉じる",
  cancel: "キャンセル",
  moves: "棋譜",
  set_theme: "盤の色",
  theme_green: "緑",
  theme_brown: "茶",
  theme_blue: "青",
  set_pieces: "駒",
  pieces_cburnett: "標準",
  pieces_classic: "クラシック",
  set_coords: "座標を表示",
  set_autoQueen: "常にクイーンに昇格",
  set_legal: "指せる手を表示",
  settingsHint: "このチャットにだけ保存されます",
  say_move: "{who}：{piece}を{square}へ",
  say_capture: "{who}：{piece}が{square}で取る",
  say_castleK: "{who}：キングサイドにキャスリング",
  say_castleQ: "{who}：クイーンサイドにキャスリング",
  say_promote: "{piece}に昇格",
  say_check: "チェック",
  say_mate: "チェックメイト",
  nav: "対局を振り返る",
  nav_first: "最初の手",
  nav_prev: "前の手",
  nav_play: "手を再生",
  nav_pause: "一時停止",
  nav_next: "次の手",
  nav_last: "最後の手",
  backToLive: "対局に戻る",
  review: "振り返る",
  opening: "オープニング",
  sound: "サウンド",
  taken: "取った駒: {pieces}",
  ahead: "{n} 点リード",
  copyPgn: "PGN をコピー",
  pgnTitle: "PGN の棋譜",
  copy: "コピー",
  copied: "コピーしました",
  copyByHand: "選択したテキストをコピーしてください（スマートフォンでは長押し）。",
  why_time: "時間切れ",
  why_aborted: "中止",
  why_disputed: "時計の不一致",
  noResult: "結果なし",
  notice_declined: "相手が招待を断りました。",
  setupTitle: "新しい対局",
  setupHint: "白番は抽選で決まります。",
  tc_unlimited: "無制限",
  tc_bullet: "バレット",
  tc_blitz: "ブリッツ",
  tc_rapid: "ラピッド",
  tc_classical: "クラシカル",
  tc_words: "{kind}・{min}分",
  tc_wordsInc: "{kind}・{min}分+{inc}秒",
  invite: "招待",
  setupStatus: "相手を対局に招待しましょう",
  invitedStatus: "招待を送りました",
  invitedAway: "相手がチェスを開くと招待が届きます。",
  invitesYou: "相手からの招待: {terms}",
  rematchYou: "再戦しますか？（{terms}）",
  canStillMove: "指し手はまだ指せます。相手が戻ると届きます。",
  compatBanner: "相手のチェスは {version} です。時計、待った、再戦は相手が更新すると使えます。",
  compatBannerOld: "相手のチェスは古いバージョンです。時計、待った、再戦は相手が更新すると使えます。",
  compatInfo: "詳細",
  compatDetails: "相手のチェスはゲームのプロトコルの最初の版を使います。時計なしで対局し、始めた対局はどちらかが更新しても続きます。Ghostly は起動時、1日1回、アプリのページでアプリを更新します。",
  needsUpdate: "相手がチェスを更新する必要があります（{version} を使用中）",
  needsUpdateOld: "相手がチェスを更新する必要があります",
  comingSoon: "今後のバージョンで使えるようになります",
  why_timeMaterial: "時間切れ(相手の駒不足)",
  notice_clockOff: "相手の時計がずれているようです。",
  peerSilent: "相手のチェスが応答していません",
  pendingClaim: "相手の時間がなくなりそうです。相手のチェスが戻ると対局が終わります。",
  say_secondsLeft: "残り{n}秒",
  takeback: "待った",
  takebackAsked: "待ったを申請済み",
  peerAsksTakeback: "相手が待ったを求めています",
  takenBack: "一手戻しました",
  notice_takebackDeclined: "相手が待ったを断りました。",
  rematch: "再戦",
  resignAsk: "この対局を投了しますか？",
  abort: "中止",
  set_premove: "先行入力を使う",
  premove: "先行入力",
};

export const zh: Strings = {
  title: "国际象棋",
  board: "棋盘",
  loading: "加载中…",
  alone: "你在同时执两方。在聊天中打开国际象棋即可和联系人对弈。",
  waitingPeer: "等待联系人打开国际象棋",
  tossing: "正在决定执棋颜色…",
  yourMove: "轮到你",
  theirMove: "轮到对方",
  whiteToMove: "白方走",
  blackToMove: "黑方走",
  youAreWhite: "你执白",
  youAreBlack: "你执黑",
  check: "将军",
  away: "联系人关闭了国际象棋。对局在这里等着。",
  outOfStep: "你们的对局不一致。要开始新的一局吗？",
  won: "你赢了",
  lost: "你输了",
  whiteWins: "白方胜",
  blackWins: "黑方胜",
  drawn: "和棋",
  why_checkmate: "将死",
  why_stalemate: "逼和",
  why_repetition: "三次重复",
  why_fifty: "50 步规则",
  why_material: "子力不足",
  why_limit: "步数上限",
  why_resign: "认输",
  why_agreed: "协议",
  peerOffersDraw: "联系人提议和棋",
  youOfferedDraw: "已提议和棋",
  offerDraw: "提议和棋",
  accept: "接受",
  decline: "拒绝",
  resign: "认输",
  newGame: "新对局",
  promoteTo: "升变为",
  notice_invalidMove: "已忽略联系人的一步无效着法。",
  notice_badMessage: "已忽略一条国际象棋无法读取的消息。",
  notice_tooBig: "已忽略一条过大的消息。",
  notice_newerVersion: "联系人的国际象棋版本更新。请更新后继续。",
  notice_badReveal: "决定颜色失败，正在重试。",
  notice_tossRestarted: "联系人重新开始决定颜色。",
  notice_outOfStep: "你们的对局不一致。",
  notice_peerNewGame: "联系人开始了新对局。",
  notice_sendFailed: "未发送。联系人回来后会发出。",
  white: "白",
  black: "黑",
  piece: "{colour}{piece}",
  empty: "空",
  selected: "已选中",
  canMoveHere: "可走到这里",
  lastMove: "上一步",
  piece_k: "王",
  piece_q: "后",
  piece_r: "车",
  piece_b: "象",
  piece_n: "马",
  piece_p: "兵",
  you: "你",
  contact: "联系人",
  whiteName: "白方",
  blackName: "黑方",
  flip: "翻转棋盘",
  settings: "设置",
  close: "关闭",
  cancel: "取消",
  moves: "着法",
  set_theme: "棋盘颜色",
  theme_green: "绿色",
  theme_brown: "棕色",
  theme_blue: "蓝色",
  set_pieces: "棋子",
  pieces_cburnett: "标准",
  pieces_classic: "经典",
  set_coords: "显示坐标",
  set_autoQueen: "总是升变为后",
  set_legal: "显示可走位置",
  settingsHint: "仅保存在此聊天中",
  say_move: "{who}：{piece}走到{square}",
  say_capture: "{who}：{piece}在{square}吃子",
  say_castleK: "{who}：王翼易位",
  say_castleQ: "{who}：后翼易位",
  say_promote: "升变为{piece}",
  say_check: "将军",
  say_mate: "将死",
  nav: "回顾对局",
  nav_first: "第一步",
  nav_prev: "上一步",
  nav_play: "播放着法",
  nav_pause: "暂停",
  nav_next: "下一步",
  nav_last: "最后一步",
  backToLive: "回到对局",
  review: "回顾",
  opening: "开局",
  sound: "声音",
  taken: "吃掉: {pieces}",
  ahead: "领先 {n}",
  copyPgn: "复制 PGN",
  pgnTitle: "PGN 棋谱",
  copy: "复制",
  copied: "已复制",
  copyByHand: "请复制选中的文字（手机上长按）。",
  why_time: "超时",
  why_aborted: "已中止",
  why_disputed: "棋钟不一致",
  noResult: "无结果",
  notice_declined: "联系人拒绝了邀请。",
  setupTitle: "新对局",
  setupHint: "由抽签决定谁执白。",
  tc_unlimited: "不限时",
  tc_bullet: "子弹棋",
  tc_blitz: "闪电棋",
  tc_rapid: "快棋",
  tc_classical: "慢棋",
  tc_words: "{kind}，{min} 分钟",
  tc_wordsInc: "{kind}，{min} 分钟 + {inc} 秒",
  invite: "邀请",
  setupStatus: "邀请联系人来下一局",
  invitedStatus: "邀请已发送",
  invitedAway: "联系人打开国际象棋时，邀请就会送达。",
  invitesYou: "联系人邀请你：{terms}",
  rematchYou: "再来一局？（{terms}）",
  canStillMove: "你仍然可以走棋。联系人回来时就会送达。",
  compatBanner: "联系人的国际象棋是 {version} 版。棋钟、悔棋和再来一局要等对方更新后才有。",
  compatBannerOld: "联系人的国际象棋版本较旧。棋钟、悔棋和再来一局要等对方更新后才有。",
  compatInfo: "说明",
  compatDetails: "对方的国际象棋使用第一版游戏协议：你们下不限时的对局，已开始的对局在任一方更新后仍会继续。Ghostly 会在启动时、每天一次以及在应用页面更新应用。",
  needsUpdate: "联系人需要更新国际象棋（对方是 {version} 版）",
  needsUpdateOld: "联系人需要更新国际象棋",
  comingSoon: "将在国际象棋的后续版本中提供",
  why_timeMaterial: "超时（对方子力不足）",
  notice_clockOff: "联系人的棋钟似乎不准。",
  peerSilent: "联系人的国际象棋没有响应",
  pendingClaim: "联系人的时间快用完了。对方的国际象棋回来时对局结束。",
  say_secondsLeft: "还剩 {n} 秒",
  takeback: "悔棋",
  takebackAsked: "已请求悔棋",
  peerAsksTakeback: "联系人请求悔棋",
  takenBack: "已悔一步",
  notice_takebackDeclined: "联系人拒绝了悔棋。",
  rematch: "再来一局",
  resignAsk: "认输这局？",
  abort: "中止",
  set_premove: "允许预走",
  premove: "预走",
};

export const ar: Strings = {
  title: "الشطرنج",
  board: "رقعة الشطرنج",
  loading: "جارٍ التحميل…",
  alone: "تلعب بالطرفين. افتح الشطرنج في محادثة لتلعب مع جهة اتصالك.",
  waitingPeer: "بانتظار أن تفتح جهة اتصالك الشطرنج",
  tossing: "جارٍ اختيار الألوان…",
  yourMove: "دورك",
  theirMove: "دور جهة اتصالك",
  whiteToMove: "دور الأبيض",
  blackToMove: "دور الأسود",
  youAreWhite: "تلعب بالأبيض",
  youAreBlack: "تلعب بالأسود",
  check: "كش",
  away: "أغلقت جهة اتصالك الشطرنج. اللعبة تنتظر هنا.",
  outOfStep: "لعبتاكما مختلفتان. هل تبدأ لعبة جديدة؟",
  won: "فزت",
  lost: "خسرت",
  whiteWins: "فاز الأبيض",
  blackWins: "فاز الأسود",
  drawn: "تعادل",
  why_checkmate: "كش مات",
  why_stalemate: "جمود",
  why_repetition: "تكرار ثلاثي",
  why_fifty: "قاعدة الخمسين نقلة",
  why_material: "قطع غير كافية",
  why_limit: "حد النقلات",
  why_resign: "استسلام",
  why_agreed: "اتفاق",
  peerOffersDraw: "تعرض جهة اتصالك التعادل",
  youOfferedDraw: "عُرض التعادل",
  offerDraw: "اعرض التعادل",
  accept: "قبول",
  decline: "رفض",
  resign: "استسلام",
  newGame: "لعبة جديدة",
  promoteTo: "ترقية إلى",
  notice_invalidMove: "تم تجاهل نقلة غير صالحة من جهة اتصالك.",
  notice_badMessage: "تم تجاهل رسالة لم يستطع الشطرنج قراءتها.",
  notice_tooBig: "تم تجاهل رسالة كبيرة جدًا.",
  notice_newerVersion: "لدى جهة اتصالك إصدار أحدث من الشطرنج. حدّث لتواصل اللعب.",
  notice_badReveal: "فشل اختيار الألوان. جارٍ المحاولة مجددًا.",
  notice_tossRestarted: "أعادت جهة اتصالك اختيار الألوان.",
  notice_outOfStep: "لعبتاكما مختلفتان.",
  notice_peerNewGame: "بدأت جهة اتصالك لعبة جديدة.",
  notice_sendFailed: "لم تُرسل. ستُرسل عند عودة جهة اتصالك.",
  white: "أبيض",
  black: "أسود",
  piece: "{piece} {colour}",
  empty: "فارغ",
  selected: "محدد",
  canMoveHere: "انقل إلى هنا",
  lastMove: "آخر نقلة",
  piece_k: "ملك",
  piece_q: "وزير",
  piece_r: "رخ",
  piece_b: "فيل",
  piece_n: "حصان",
  piece_p: "بيدق",
  you: "أنت",
  contact: "جهة اتصالك",
  whiteName: "الأبيض",
  blackName: "الأسود",
  flip: "اقلب الرقعة",
  settings: "الإعدادات",
  close: "إغلاق",
  cancel: "إلغاء",
  moves: "النقلات",
  set_theme: "ألوان الرقعة",
  theme_green: "أخضر",
  theme_brown: "بني",
  theme_blue: "أزرق",
  set_pieces: "القطع",
  pieces_cburnett: "قياسية",
  pieces_classic: "كلاسيكية",
  set_coords: "إظهار الإحداثيات",
  set_autoQueen: "الترقية إلى وزير دائمًا",
  set_legal: "إظهار النقلات الممكنة",
  settingsHint: "تُحفظ لهذه المحادثة فقط",
  say_move: "{who}: {piece} إلى {square}",
  say_capture: "{who}: {piece} يأسر في {square}",
  say_castleK: "{who}: تبييت قصير",
  say_castleQ: "{who}: تبييت طويل",
  say_promote: "يترقى إلى {piece}",
  say_check: "كش",
  say_mate: "كش مات",
  nav: "مراجعة اللعبة",
  nav_first: "النقلة الأولى",
  nav_prev: "النقلة السابقة",
  nav_play: "تشغيل النقلات",
  nav_pause: "إيقاف مؤقت",
  nav_next: "النقلة التالية",
  nav_last: "النقلة الأخيرة",
  backToLive: "العودة إلى اللعبة",
  review: "مراجعة",
  opening: "الافتتاح",
  sound: "الأصوات",
  taken: "أخذ: {pieces}",
  ahead: "متقدم بـ {n}",
  copyPgn: "نسخ PGN",
  pgnTitle: "اللعبة بصيغة PGN",
  copy: "نسخ",
  copied: "تم النسخ",
  copyByHand: "انسخ النص المحدد (على الهاتف، اضغط عليه مطولًا).",
  why_time: "انتهاء الوقت",
  why_aborted: "أُلغيت",
  why_disputed: "اختلاف الساعتين",
  noResult: "بلا نتيجة",
  notice_declined: "رفضت جهة اتصالك الدعوة.",
  setupTitle: "لعبة جديدة",
  setupHint: "القرعة تحدد من يلعب بالأبيض.",
  tc_unlimited: "بلا حد",
  tc_bullet: "رصاصية",
  tc_blitz: "خاطفة",
  tc_rapid: "سريعة",
  tc_classical: "كلاسيكية",
  tc_words: "{kind}، {min} د",
  tc_wordsInc: "{kind}، {min} د + {inc} ث",
  invite: "دعوة",
  setupStatus: "ادعُ جهة اتصالك إلى لعبة",
  invitedStatus: "أُرسلت الدعوة",
  invitedAway: "تصل دعوتك عندما تفتح جهة اتصالك الشطرنج.",
  invitesYou: "تدعوك جهة اتصالك: {terms}",
  rematchYou: "مباراة ثأرية؟ ({terms})",
  canStillMove: "ما زال بإمكانك أن تلعب نقلتك. تصل عندما تعود جهة اتصالك.",
  compatBanner: "لدى جهة اتصالك الشطرنج {version}. الساعات والتراجع عن النقلات والمباريات الثأرية تأتي عندما تحدّث التطبيق.",
  compatBannerOld: "لدى جهة اتصالك إصدار أقدم من الشطرنج. الساعات والتراجع عن النقلات والمباريات الثأرية تأتي عندما تحدّث التطبيق.",
  compatInfo: "حول هذا",
  compatDetails: "يتحدث شطرنج جهة اتصالك الإصدار الأول من بروتوكول اللعبة: تلعبان دون ساعة، وتستمر اللعبة التي بدأتماها عندما يحدّث أي منكما. يحدّث Ghostly التطبيقات عند البدء ومرة يوميًا وفي صفحة التطبيقات.",
  needsUpdate: "على جهة اتصالك تحديث الشطرنج (لديها {version})",
  needsUpdateOld: "على جهة اتصالك تحديث الشطرنج",
  comingSoon: "يأتي في إصدار لاحق من الشطرنج",
  why_timeMaterial: "انتهاء الوقت مع قطع غير كافية للخصم",
  notice_clockOff: "يبدو أن ساعة جهة اتصالك غير مضبوطة.",
  peerSilent: "الشطرنج لا يستجيب لدى جهة اتصالك",
  pendingClaim: "وقت جهة اتصالك ينفد. تنتهي اللعبة عندما يعود الشطرنج لديها.",
  say_secondsLeft: "بقيت {n} ثانية",
  takeback: "تراجع عن النقلة",
  takebackAsked: "طُلب التراجع",
  peerAsksTakeback: "تطلب جهة اتصالك التراجع عن نقلة",
  takenBack: "تم التراجع عن النقلة",
  notice_takebackDeclined: "رفضت جهة اتصالك التراجع.",
  rematch: "مباراة ثأرية",
  resignAsk: "تستسلم في هذه اللعبة؟",
  abort: "إلغاء المباراة",
  set_premove: "السماح بالنقلات المسبقة",
  premove: "نقلة مسبقة",
};
